Edit run job, run-docker

diff --git a/deploy/bin/run-job b/deploy/bin/run-job
--- a/deploy/bin/run-job
+++ b/deploy/bin/run-job
@@ -1,36 +1,37 @@
 #!/usr/bin/env bash
 set -eou pipefail
 
-dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-src_dir="${dir}/../../src"
+dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../../" && pwd )" && cd "$dir"
+src_dir="${dir}/src"
 set +u; _job="$1"; set -u
 cmd=''
 
+update_crond(){
+  case "$(uname)" in
+    ('FreeBSD') sed -i '1i SHELL=/usr/local/bin/bash' "${dir}/deploy/tasks/crontab"
+                sed -i '1i cmd="deploy/bin/run-job'   "${dir}/deploy/tasks/crontab" ;;
+  esac
+  sudo cp "${dir}/deploy/tasks/crontab" >"/etc/cron.d/${app}"
+}
+
 prereqs(){
   if [[ $(whoami) == 'root' ]]; then
-    case $(uname -a) in
-      *arm* )
-        set +e; eval "${dir}/apk-arm"; update-ca-certificates; apk fix || echo 'Unable to reach apk...'; set -e; ;; # set +e when apk not available
-    esac
-
-    case $(cat /etc/os-release | grep -i '^name=' | sed 's/NAME=//' | sed 's/^"\(.*\)"$/\1/') in
-      'Alpine Linux' )
-        update-ca-certificates; apk fix || echo 'Unable to reach apk...' ;; # Any quirks with Alpine can go here
-      'Debian GNU/Linux' )
-        echo '' ;; # Any quirks with Debian can go here
+    case $(uname -m) in
+      arm* )
+        deploy_dir='/usr/local/deploy/bin'
+        set +e; eval "${deploy_dir}/apk-arm"; update-ca-certificates; apk fix || echo 'Unable to reach apk...'; set -e; # set +e when apk not available
     esac
   fi
 }
+
+if [[ $(uname) == 'FreeBSD' ]]; then update_crond; fi
 
 case "$_job" in
   daily )
     cmd="${src_dir}/run-it daily" ;;
   weekly )
     cmd="${src_dir}/run-it weekly" ;;
-  * )
-    cmd="${src_dir}/run-it daily" ;;
-  #* )  # uncomment after testing lambda
-    #echo 'No args provided' && exit 1 ;;
+  * ) echo 'No args provided' && exit 1 ;;
 esac
 
 prereqs && \
